name: Export New Qbot Image
on:
  workflow_dispatch:

jobs:
  pull-and-export:
    runs-on: ubuntu-latest
    steps:
      - name: Pull New Image
        # 换成这个目前确定存活且好用的镜像
        run: docker pull ddsderek/xiaoya-qbittorrent-bot:latest

      - name: Save Image
        run: docker save ddsderek/xiaoya-qbittorrent-bot:latest > new_qbot.tar

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: new-qbot-package
          path: new_qbot.tar
