name: Export Moerats Image
on:
  workflow_dispatch: # 手动触发

jobs:
  build-and-export:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Moerats Image
        run: docker pull moerats/qbittorrentbot:latest

      - name: Save Image to Tar
        run: docker save moerats/qbittorrentbot:latest > moerats_qbot.tar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: moerats-package
          path: moerats_qbot.tar
          retention-days: 1
